services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
